config/routes.rb
Sport::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  devise_for :users 
      
 resources :users, only: [:index, :show]
  post '/user_search' => "users#search"
  get '/user_index_search' => "users#index_search"
  get '/user_email_index_search' => "users#email_index_search"
  resources :friendships
  get '/incoming_requests' => "friendships#incoming"
  get '/outgoing_requests' => "friendships#outgoing"
  get '/reverse_messages' => "messages#reverse"
  resources :messages 
  post '/receiver_search' => "messages#receiver_search"
  get 'chats' => "messages#chat_index"
  get 'chat/:id' => "messages#chat_show", as: 'chat'
  
  resources :microposts
  post '/micropost_search' => "microposts#search"
  

  get '/events_master' => "events#master"
  get '/events_all' => "events#all"
  get '/events_joined' => "events#joined"
  post '/event_search' => "events#search"
  get '/event_index_search' => "events#index_search"
  resources :events do
    post :join
 end

 

  root to: 'home#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :content, :receiver_id, :sender_id

  belongs_to :receiver, class_name: "User"
  belongs_to :sender, class_name: "User"

  validates :content, presence: true
  validates :sender_id, presence: true
  validates :receiver_id, presence: true
  
  scope :all_messages_with_user, lambda {
    |user_id| where("receiver_id = ? OR sender_id = ?", user_id, user_id).order("created_at DESC")  
  }

  scope :chat_with_friend, lambda{
    |user_id,friend_id|  where("( receiver_id= (?)  AND sender_id= (?)  ) OR ( receiver_id= (?)  AND sender_id= (?)  )",
     user_id, friend_id, friend_id, user_id).order("created_at DESC")
  }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @title = "Messages"
    @messages = current_user.messages.paginate(page: params[:page])
    @users = @messages.map { |message| User.find(message.receiver_id) }
  end
  
  def reverse
    @title = "Reverse Messages"
    @messages = current_user.reverse_messages.paginate(page: params[:page])
    @users = @messages.map { |message| User.find(message.sender_id) }
    
  end

   def chat_show
    @title = "Chat with"
    @messages = Message.chat_with_friend(current_user.id,params[:id]).paginate(page: params[:page])
    @message = Message.new
  end
 

  def chat_show
    @title = "Chat with"
    @messages = Message.chat_with_friend(current_user.id,params[:id]).paginate(page: params[:page])
    @message = Message.new
    @title=User.find(params[:id]).first_name
    @senders = []
    @senders = @messages.map { |message| User.find(message.sender_id).email }
    @receivers = []
    @receivers = @messages.map { |message| User.find(message.receiver_id).email }
    @receiver_email = current_user.giv_chat_user(@messages[0]).email
  end
  
  def chat_index
    @title = "Chats"
    @messages = current_user.all_chats_with_user.map { |chat| chat[:message] }.paginate(page: params[:page])
    @count = current_user.all_chats_with_user.map { |chat| chat[:count] }
    @chat_users = @messages. map { |message| current_user.giv_chat_user(message) }
  end

  def show
    @message = Message.find(params[:id])
    @sender=User.find(@message.sender_id).email
    @receiver=User.find(@message.receiver_id).email
  end

  def new
    @message = Message.new
  end

  def edit
    @message = Message.find(params[:id])
  end

  def create
    email = params[:receiver_email].present? ? params[:receiver_email] : params[:Message_to_user][:receiver_email]
    chat = true if params[:receiver_email].present?
    if a = User.find_by_email(email)
      receiver_id =  a.id
      @message = current_user.messages.build(
      content: params[:Message_to_user][:content], 
      receiver_id: receiver_id
      )
      if @message.save
        redirect_to (chat ? chat_path(receiver_id) : @message), notice: 'Message was successfully created.'
      else
        flash[:error] = 'Something wrong'
        render "new"
      end
    else
      flash[:error] = 'Email incorrect'
      redirect_to new_message_path
    end
  end
  
  def update
    @message = Message.find(params[:id])
    
    if @message.update_attributes(params[:message])
      redirect_to @message, notice: 'Message was successfully updated.'
    else
      render "edit"
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy
    
    redirect_to messages_url
  end
end

app/views/messages/_form.html.erb
<% @message_to_user="Message_to_user" %>
<%= form_for @message_to_user, :url => messages_path(@message_to_user) do |f| %>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class=>'redactor' %>
    </div>
  </div>

    <div class="control-group">
     <%= f.label  ("Search by users email") %><br />
     <div class="controls">
      <%= f.text_field :receiver_email, data: { autocomplete_source: user_email_index_search_path } %>
       </div> 
</div>
 <div class="form-actions">
    <%= f.submit "Send",:class => 'btn btn-primary'%>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                messages_path, :class => 'btn' %>
                  </div>
<% end %>

app/views/messages/_index.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => title %><%= link_to '/Chats', chats_path %></h1>
</div>
<%= will_paginate %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:content) %></th>
    <% if params[:action] == "reverse" %>
      <th><%= model_class.human_attribute_name(:sender) %></th>
      <% else %>
      <th><%= model_class.human_attribute_name(:receiver) %></th>
      <% end %>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', default: t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% messages.each_with_index do |message, i| %>
      <tr>
        <td><%= link_to message.content.html_safe, message_path(message) %></td>
        <td><%= users[i].email %></td>
        <td><%=l message.created_at %></td>
         <td>
          <% if current_user.id == message.sender_id %>
          <%= link_to t('.edit', default: t("helpers.links.edit")),
                      edit_message_path(message), class: 'btn btn-mini' %>
          <%= link_to t('.destroy', default: t("helpers.links.destroy")),
                      message_path(message),
                      method: :delete,
                      confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')),
                      class: 'btn btn-mini btn-danger' %>
                      <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>

app/views/messages/chat_index.html.erb
<%- model_class = Message -%>

<div class="page-header">
  <h1><%= link_to 'Messages/', messages_path %><%=t '.title', :default => @title %></h1>
</div>

<%= will_paginate %>


<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th>Chat with:</th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th>Count</th>
    </tr>
  </thead>
<% if @messages.present? %>
  <tbody>
    <% @messages.each_with_index do |message, i| %>
      <tr>
        <td><%= link_to message.content.html_safe, chat_path(@chat_users[i].id) %></td>
        <td><%= link_to @chat_users[i].email, chat_path(@chat_users[i].id) %></td>
        <td><%=l message.created_at %></td>
        <td><%= @count[i] %></td>
      </tr>
      <% end %>
  <% end %>
  </tbody>
</table>


<%= will_paginate %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_message_path,
            :class => 'btn btn-primary' %>

app/views/messages/chat_show.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => @title %> <%= @title%>
  </h1>
</div>
<%= will_paginate %>

<table class="table table-striped">
  <thead>
    <tr>
      
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:sender) %></th>
      <th><%= model_class.human_attribute_name(:receiver) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @messages.each_with_index do |message, i | %>
      <tr><td><%= link_to message.content.html_safe, message_path(message) %></td>
        <td><%= @senders[i] %></td>
        <td><%= @receivers[i] %></td>
        <td><%=l message.created_at %></td>
        <td>
          <% if message.sender == current_user %>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_message_path(message), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      message_path(message),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
            <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>

<%= link_to 'Chats', chats_path, :class => 'btn' %>


 
<div class="page-header">
</div>


<% @message_to_user="Message_to_user" %>
<%= form_for @message_to_user, :url => messages_path(@search) do |f| %>
 <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
     <%= f.text_area :content, :class=>'redactor' %>
     
  </div>
    </div>
   <div class="form-actions">
      <%= hidden_field_tag(:receiver_email, @receiver_email) %>
    <%= f.submit "Send",:class => 'btn btn-primary'%>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                messages_path, :class => 'btn' %>
                  </div>
<% end %>

app/views/messages/edit.html.erb
<%- model_class = Message -%>

<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>

<%= form_for @message, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class=>'redactor'%>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                messages_path, :class => 'btn' %>
  </div>
<% end %>

app/views/messages/index.html.erb
<%= render partial: 'index', locals: { users: @users, messages: @messages, title: @title } %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_message_path,
            :class => 'btn btn-primary' %>
<%= link_to 'Reverse', reverse_messages_path, :class => 'btn' %>

app/views/messages/new.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render 'form' %>

app/views/messages/reverse.html.erb
<%= render partial: 'index', locals: { users: @users, messages: @messages, title: @title } %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_message_path,
            :class => 'btn btn-primary' %>
<%= link_to 'Messages', messages_path, :class => 'btn' %>

app/views/messages/show.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @message.content.html_safe %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sender_id) %>:</strong></dt>
  <dd><%= @sender %></dd>
  <dt><strong><%= model_class.human_attribute_name(:receiver_id) %>:</strong></dt>
  <dd><%= @receiver %></dd>
</dl>

<div class="form-actions">
  <% if current_user.id==@message.sender_id %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_message_path(@message), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              message_path(@message),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
              <% end %>
</div>