config/routes.rb
Sport::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  devise_for :users 
      
 resources :users, only: [:index, :show]
  post '/user_search' => "users#search"
  get '/user_index_search' => "users#index_search"
  get '/user_email_index_search' => "users#email_index_search"
  resources :friendships
  get '/incoming_requests' => "friendships#incoming"
  get '/outgoing_requests' => "friendships#outgoing"
  get '/reverse_messages' => "messages#reverse"
  resources :messages 
  post '/receiver_search' => "messages#receiver_search"
  get 'chats' => "messages#chat_index"
  get 'chat/:id' => "messages#chat_show", as: 'chat'
  
  resources :microposts
  post '/micropost_search' => "microposts#search"
  

  get '/events_master' => "events#master"
  get '/events_all' => "events#all"
  get '/events_joined' => "events#joined"
  post '/event_search' => "events#search"
  get '/event_index_search' => "events#index_search"
  resources :events do
    post :join
 end

 

  root to: 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :birth_date, :description, :email, :first_name,
    :last_name,:email, :password, :password_confirmation, :remember_me

  has_many :microposts, dependent: :destroy

  has_many :users_events, dependent: :destroy
  has_many :events, through: :users_events
  has_many :master_events, through: :users_events,
    source: :event, conditions: [ "role = ?", true]

  has_many :messages, foreign_key: "sender_id", dependent: :destroy
  has_many :reverse_messages, class_name: "Message",
    foreign_key: "receiver_id", dependent: :destroy

  has_many :receivers, through: :messages, source: :receiver
  has_many :senders, through: :reverse_messages, source: :sender

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships,
    source: :user, conditions: [ "authorized = ?", false ]
  
  has_many :my_authorized_friends, through: :friendships,
    source: :friend, conditions: [ "authorized = ?", true ]
  has_many :inverse_authorized_friends, through: :inverse_friendships,
    source: :user, conditions: [ "authorized = ?", true ]
  has_many :unauthorized_friends, through: :friendships,
    source: :friend, conditions: [ "authorized = ?", false ]

  scope :friends_wich_accepted,  lambda {
    |my_id|   User.find(my_id).my_authorized_friends + User.find(my_id).inverse_authorized_friends }
  
  validates_date :birth_date, before: lambda { 18.years.ago },
    before_message: "must be at least 18 years old"

  # FRIENDSHIP METHODS - BEGIN
  def can_add_to_friends?(friend)
    !my_friend?(friend) && !(id == friend.id)
  end
  
  def my_friend?(friend)
    Friendship.my_friends(id, friend.id).present?
  end
  
  def add_to_friends!(friend)
    friendships.create!(friend: friend)
  end
  # FRIENDSHIP METHODS - END
  
  # EVENTS METHODS - BEGIN
  def find_user_event(event)
    users_events.where(event_id: event.id).first
  end
  
  def can_join?(event)
    find_user_event(event).blank?
  end

  def can_edit_event?(event)
    user_event = find_user_event(event)
    user_event.present? && user_event.role?
  end
  
  def join_event!(event)
    if can_join?(event)
       users_events.create(event_id: event.id)
       event.update_attributes(members: event.members + 1)
    end
  end
   # EVENTS METHODS - END

   # MESSAGES METHODS - BEGIN
  def unique_ids(all_messages)
    all_id_pairs = all_messages.map { |c| [c.sender_id, c.receiver_id] }
    unique_ids = all_id_pairs.flatten
    unique_ids = unique_ids.uniq.reject! { |i| i == id }
  end

  def chat_with
    all_messages = Message.all_messages_with_user(id)
    chat_pairs = []
    unique_ids(all_messages).each_with_index do |unique_id|
      chat_pairs << all_messages.
        select { |c| c.sender_id == unique_id || c.receiver_id == unique_id }
    end
    chat_pairs
  end

  def all_chats_with_user
    chats = []
    chat_with.each_with_index do | message, i| 
      chats[i] = { message: message[0], count: message.size }
      end
      chats
  end
 
    def giv_chat_user(message)
      if message.sender_id == id
        User.find(message.receiver_id)
      else
        User.find(message.sender_id)
      end
    end


  # MESSAGES METHODS - END
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @users = User.all.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def search
    @user = User.find_by_last_name(params[:Search][:title123])
    
    redirect_to ( @user.present? ? @user : users_path)
  end

  def index_search
    @users = User.order(:last_name).where("last_name like ?", "%#{params[:term]}%")
    render json: @users.map(&:last_name)
  end

  def email_index_search
    @users = User.order(:email).where("email like ?", "%#{params[:term]}%")
    render json: @users.map(&:email)
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { size: 50 })
    gravatar_image_tag(user.email.downcase, alt: user.first_name,
                                            class: 'gravatar',
                                            gravatar: options)
  end
end

app/views/users/index.html.erb
<%- model_class = User -%>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<%= will_paginate %>

<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:birth_date) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= gravatar_for user, :size => 30 %></td>
        <td><%= link_to user.first_name, user_path(user) %></td>
        <td><%= user.last_name %></td>
        <td><%= user.birth_date %></td>
        <% if current_user.can_add_to_friends?(user) %>
        <td><%= link_to 'Add to friends', friendships_path(user), method: :post, :class => 'btn' %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate %>

<%= form_for "Search", :url => user_search_path("Search") do |f| %>
  <div class="field">
    <%= f.label  ("Search by users last name") %><br />
    <%= f.text_field :title1234, data: { autocomplete_source: user_index_search_path } %>
  </div> <%= f.submit "Search"%>
<% end %>

<a id="inline" href="#data">This shows content of element who has id="data"</a>

<div style="display:none"><div id="data">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</div></div>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1>
    <%= gravatar_for @user, :size => 50 %>
    <%=t '.title', :default => @user.first_name %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @user.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @user.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:birth_date) %>:</strong></dt>
  <dd><%= @user.birth_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @user.description.html_safe %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>

  <% if @user.id==current_user.id %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_registration_path, :class => 'btn' %>
              <% end %>
  <% if current_user.can_add_to_friends?(@user) %>
   <%= link_to 'Add to friends', friendships_path(@user), :method => :post, :class => 'btn' %>           
  <% end %>

</div>
<% if @user.microposts.any? %>
<h2>Microposts</h2>
<table class="table table-striped">
  <thead>
    <tr>

      <th>Content</th>
      <% if @user.id==current_user.id %>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @user.microposts.each do |micropost| %>
      <tr>
        <td><%= link_to micropost.content, micropost_path(micropost) %></td>
        
        <% if @user.id==current_user.id %>        
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_micropost_path(micropost), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      micropost_path(micropost),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>