config/routes.rb
Sport::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  devise_for :users 
      
 resources :users, only: [:index, :show]
  post '/user_search' => "users#search"
  get '/user_index_search' => "users#index_search"
  get '/user_email_index_search' => "users#email_index_search"
  resources :friendships
  get '/incoming_requests' => "friendships#incoming"
  get '/outgoing_requests' => "friendships#outgoing"
  get '/reverse_messages' => "messages#reverse"
  resources :messages 
  post '/receiver_search' => "messages#receiver_search"
  get 'chats' => "messages#chat_index"
  get 'chat/:id' => "messages#chat_show", as: 'chat'
  
  resources :microposts
  post '/micropost_search' => "microposts#search"
  

  get '/events_master' => "events#master"
  get '/events_all' => "events#all"
  get '/events_joined' => "events#joined"
  post '/event_search' => "events#search"
  get '/event_index_search' => "events#index_search"
  resources :events do
    post :join
 end

 

  root to: 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :description, :event_date, :members, :title, :latitude, :longitude, :photo, :result

  has_many :users_events, dependent: :destroy
  has_many :users, through: :users_events
  
  has_attached_file :photo

  validates :title, presence: true, length: { maximum: 140 }
  validates :members, presence: true
  validates :event_date, presence: true
  validates :description, presence: true, length: { maximum: 1500 }
  
  scope :with_coordinates, where("latitude is not NULL AND longitude is not NULL")
  
  def event_title=(title)
    Category.find_by_title(title) if title.present?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @title = "My events"
    @titlesearch
    @events = current_user.events.paginate(page: params[:page])
  end

  def master
    @title="Events that i create"
    @events = current_user.master_events.paginate(page: params[:page])
  end

  def joined
    @title="Joined events"
    users_events = current_user.users_events.where(role: false)
    events = []
    users_events.each do |user_event|
      events << user_event.event
    end
    events.compact!
    @events = events.paginate(page: params[:page])
  end

  def all
    @title = "All events"
    @events = Event.paginate(page: params[:page])
  end

  def show
    @event = Event.find(params[:id])
    @width = 500
    @latitude = @event.latitude
    @longitude = @event.longitude
    @zoom = 12
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(params[:event].merge(members: 1))
    if @event.valid?
      @event = current_user.events.create(params[:event].merge(members: 1))
      user_event = current_user.users_events.where(event_id: @event.id).first
      user_event.update_attributes(role: true) if user_event.present?
      flash[:notice] = 'Event was successfully created.'
      redirect_to event_url(@event)
    else
      render "new"
    end
  end

  def update
    @event = Event.find(params[:id])
    
    if @event.update_attributes(params[:event])
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render "edit"
    end
  end

  def join
    @event = Event.find(params[:event_id])
    if current_user.join_event!(@event)
      flash.now[:success] = "You could not join to this event"
    else
      flash.now[:error] = "You have joined to this event"
    end
    
    redirect_to events_path
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to events_url
  end

  def search
    if @event = Event.find_by_title(params[:Search][:title123])
      redirect_to @event
    else
      redirect_to events_path
    end
  end

  def index_search
    @events = Event.order(:title).where("title like ?", "%#{params[:term]}%")
    render json: @events.map(&:title)
  end
end

app/views/events/_form.html.erb
<%= form_for event, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class=>'redactor'%>
    </div>
  </div>
  <% if @event.created_at %>
  <div class="control-group">
    <%= f.label :result, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :result, :class=>'redactor'%>
    </div>
  </div>
  <% end %>
  <div class="control-group">
    <%= f.label :event_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.datetime_select :event_date, :class => 'datetime_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :latitude, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :latitude, :class => 'number_field' %>
    </div>
  </div>
<div class="control-group">
    <%= f.label :longitude, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :longitude, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
  <%= f.file_field :photo %>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                events_path, :class => 'btn' %>
  </div>
<% end %>

app/views/events/_index.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', default: title %></h1>
</div>
<%= will_paginate %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>   
      <th><%= model_class.human_attribute_name(:event_date) %></th>
      <th><%= model_class.human_attribute_name(:members) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% events.each do |event| %>
      <tr>
        <td><%= link_to event.title, event_path(event) %></td>
        
        <td><%= event.event_date %></td>
        <td><%= event.members %></td>
        
        <td>
          <% if current_user.can_edit_event?(event) %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_event_path(event), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      event_path(event),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_event_path,
            :class => 'btn btn-primary' %>

app/views/events/all.html.erb
<%= render 'index' %>

<%= link_to 'Joined events',  events_joined_path, :class => 'btn' %>
<%= link_to 'Created events',  events_master_path, :class => 'btn' %>
<%= link_to 'My events',  events_path, :class => 'btn' %>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render 'form', event: @event %>

app/views/events/index.html.erb
<%= render :partial => 'index', :locals => { events: @events, title: @title } %>
<%= link_to 'All events',  events_all_path, :class => 'btn' %>
<%= link_to 'Joined events',  events_joined_path, :class => 'btn' %>
<%= link_to 'Created events',  events_master_path, :class => 'btn' %>
<% @search="Search" %>
<%= form_for @search, :url => event_search_path(@search) do |f| %>
  <div class="field">
    <%= f.label  ("Search events by title") %><br />
    <%= f.text_field :title1234, data: { autocomplete_source: event_index_search_path } %>
  </div> <%= f.submit "Search"%>
<% end %>

app/views/events/join.html.erb
<h1>Join</h1>

<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @event.title %>
</p>

<p>
  <b>Description:</b>
  <%= @event.description %>
</p>

<p>
  <b>Event date:</b>
  <%= @event.event_date %>
</p>

<p>
  <b>Members:</b>
  <%= @event.members %>
</p>

<%= link_to 'Back', events_path %>

app/views/events/joined.html.erb
<%= render partial: 'index', locals: { events: @events, title: @title } %>
<%= link_to 'All events',  events_all_path, :class => 'btn' %>

<%= link_to 'Created events',  events_master_path, :class => 'btn' %>
<%= link_to 'My events',  events_path, :class => 'btn' %>

app/views/events/master.html.erb
<%= render partial: 'index', locals: { events: @events, title: @title } %>
<%= link_to 'All events',  events_all_path, :class => 'btn' %>
<%= link_to 'Joined events',  events_joined_path, :class => 'btn' %>

<%= link_to 'My events',  events_path, :class => 'btn' %>

app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<script type="text/javascript">
  function hideShowDiv(){ $('#les8_ex2').toggle('slow'); } 
</script>

<%- model_class = Event -%>
<div class="page-header">

  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>
<% if @event.photo_file_name %> 
<div id="les8_ex2" style="width:400px; height:400px">
  <%= image_tag @event.photo.url %>
</div> <input type="button" id="but1" value="Show/Hide" onclick="hideShowDiv();">
<% end %>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @event.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @event.description.html_safe %></dd>
  <% if (@event.result) %>
  <dt><strong><%= model_class.human_attribute_name(:result) %>:</strong></dt>
  <dd><%= @event.result.html_safe %></dd>
  <% end %>
  <dt><strong><%= model_class.human_attribute_name(:event_date) %>:</strong></dt>
  <dd><%= @event.event_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:members) %>:</strong></dt>
  <dd><%= @event.members %></dd>
  <% if (@event.latitude && @event.longitude) %>
  <dt><strong><%= model_class.human_attribute_name(:latitude) %>:</strong></dt>
  <dd><%= @event.latitude %></dd>
  <dt><strong><%= model_class.human_attribute_name(:longitude) %>:</strong></dt>
  <dd><%= @event.longitude %></dd>
  <% end %>
</dl>

<% if (@event.latitude && @event.longitude) %>
  <%= render  "home/index" %>
 
    <div id="map_canvas" style="width:400px; height:400px"></div>

<% end %>

<div class="form-actions">
  <% if current_user.can_join?(@event) %>
  <%= link_to 'Join', event_join_path(@event), :method => :post, :class => 'btn' %>
  <% end %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
              events_path, :class => 'btn'  %>
  <% if current_user.can_edit_event?(@event) %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_event_path(@event), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              event_path(@event),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
              <% end %>
</div>