config/routes.rb
Sport::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  devise_for :users 
      
 resources :users, only: [:index, :show]
  post '/user_search' => "users#search"
  get '/user_index_search' => "users#index_search"
  get '/user_email_index_search' => "users#email_index_search"
  resources :friendships
  get '/incoming_requests' => "friendships#incoming"
  get '/outgoing_requests' => "friendships#outgoing"
  get '/reverse_messages' => "messages#reverse"
  resources :messages 
  post '/receiver_search' => "messages#receiver_search"
  get 'chats' => "messages#chat_index"
  get 'chat/:id' => "messages#chat_show", as: 'chat'
  
  resources :microposts
  post '/micropost_search' => "microposts#search"
  

  get '/events_master' => "events#master"
  get '/events_all' => "events#all"
  get '/events_joined' => "events#joined"
  post '/event_search' => "events#search"
  get '/event_index_search' => "events#index_search"
  resources :events do
    post :join
 end

 

  root to: 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sport" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body onload="initialize()">

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand">Sport</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Home", root_path  %></li>
               <% if user_signed_in? %>
                <li><%= link_to "Users page", user_path(current_user)  %></li>
                <li><%= link_to "Messages", messages_path  %></li>
                <li><%= link_to "My microposts", microposts_path  %></li>
                <li><%= link_to "Friends", friendships_path  %></li>
                <li><%= link_to "Events", events_path  %></li>
                <li><%= link_to "Users", users_path  %></li>
                <li><% @search="Search" %>
                  <%= form_for @search, :url => event_search_path(@search) do |f| %>
                    <%= f.text_field :title123, data: { autocomplete_source: event_index_search_path } %>
                    <%= f.submit "Event Search"%>
                    <% end %>
               <% end %>
             </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header"></li>
               <li><%= link_to "Home", root_path  %></li>
                <% if user_signed_in? %>
               <li><%= link_to "Users page", user_path(current_user)  %></li>
               <li><%= link_to "Messages", messages_path  %></li>
               <li><%= link_to "My microposts", microposts_path  %></li>
               <li><%= link_to "Friends", friendships_path  %></li>
               <li><%= link_to "Events", events_path  %></li>
               <li><%= link_to "Users", users_path  %></li>
            <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
       
        <p> <% if user_signed_in? %>
          Signed in as <%= current_user.email %>. Not you?
          <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path  %>
        <% end %></p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>